services:
  - type: web
    name: crypto-ai-bot
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip wheel setuptools
      pip install -r requirements.txt
    startCommand: |
      python main.py
    healthCheckPath: /
    autoDeploy: true
